import { useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion, useInView, useAnimation } from 'framer-motion'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { ScrollToPlugin } from 'gsap/ScrollToPlugin'

gsap.registerPlugin(ScrollTrigger, ScrollToPlugin)

// ── Fade-up wrapper using Framer Motion + InView ──────────────────────────────
function FadeUp({ children, delay = 0, className = '' }) {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-80px' })
  const controls = useAnimation()

  useEffect(() => {
    if (inView) controls.start('visible')
  }, [inView, controls])

  return (
    <motion.div
      ref={ref}
      className={className}
      initial="hidden"
      animate={controls}
      variants={{
        hidden: { opacity: 0, y: 48 },
        visible: { opacity: 1, y: 0, transition: { duration: 0.65, delay, ease: [0.22, 1, 0.36, 1] } },
      }}
    >
      {children}
    </motion.div>
  )
}

// ── Data ──────────────────────────────────────────────────────────────────────
const features = [
  {
    icon: '🧠',
    title: 'AI Quizzes',
    description: 'Adaptive MCQs generated by Gemini AI across six CS subjects, tuned to your level in real time.',
    color: 'from-violet-500 to-purple-600',
    glow: 'shadow-violet-200',
  },
  {
    icon: '💻',
    title: 'Code Editor',
    description: 'Write and run Python, Java, C++, and C in-browser with Docker execution and instant AI feedback.',
    color: 'from-blue-500 to-cyan-500',
    glow: 'shadow-blue-200',
  },
  {
    icon: '🌐',
    title: 'Networking Playground',
    description: 'Drag-and-drop routers, switches, and PCs onto a canvas. AI evaluates your IP configuration.',
    color: 'from-emerald-500 to-teal-500',
    glow: 'shadow-emerald-200',
  },
  {
    icon: '🗄️',
    title: 'SQL Practice',
    description: 'Run live queries against a real SQLite database and get scored with AI-suggested corrections.',
    color: 'from-orange-500 to-amber-500',
    glow: 'shadow-orange-200',
  },
  {
    icon: '🗣️',
    title: 'English Fluency',
    description: 'Record a spoken response. Whisper + CRNN + Gemini score your grammar, pace, fillers, and pitch.',
    color: 'from-pink-500 to-rose-500',
    glow: 'shadow-pink-200',
  },
  {
    icon: '📚',
    title: 'Syllabus Browser',
    description: 'Structured syllabi for every subject so you always know exactly what to study next.',
    color: 'from-indigo-500 to-blue-600',
    glow: 'shadow-indigo-200',
  },
]

const stats = [
  { value: '6', label: 'Subjects' },
  { value: '5+', label: 'AI Tools' },
  { value: '4', label: 'Languages' },
  { value: '∞', label: 'Questions' },
]

// ── Component ─────────────────────────────────────────────────────────────────
export default function LandingPage() {
  const navigate = useNavigate()
  const heroRef = useRef(null)
  const navRef = useRef(null)
  const particlesRef = useRef(null)

  // GSAP: hero entrance + floating particles + navbar shrink on scroll
  useEffect(() => {
    const ctx = gsap.context(() => {
      // Hero text stagger
      gsap.from('.hero-line', {
        opacity: 0,
        y: 60,
        duration: 1,
        stagger: 0.18,
        ease: 'power3.out',
        delay: 0.2,
      })

      // Floating orbs
      gsap.to('.orb-1', {
        y: -30,
        x: 15,
        duration: 6,
        repeat: -1,
        yoyo: true,
        ease: 'sine.inOut',
      })
      gsap.to('.orb-2', {
        y: 25,
        x: -20,
        duration: 8,
        repeat: -1,
        yoyo: true,
        ease: 'sine.inOut',
        delay: 1,
      })
      gsap.to('.orb-3', {
        y: -20,
        x: 10,
        duration: 7,
        repeat: -1,
        yoyo: true,
        ease: 'sine.inOut',
        delay: 2,
      })

      // Navbar shrink on scroll
      ScrollTrigger.create({
        start: 'top -60',
        onEnter: () => gsap.to(navRef.current, { py: 8, duration: 0.3 }),
        onLeaveBack: () => gsap.to(navRef.current, { py: 16, duration: 0.3 }),
      })

      // Stats counter animation
      gsap.from('.stat-item', {
        opacity: 0,
        scale: 0.7,
        duration: 0.6,
        stagger: 0.12,
        ease: 'back.out(1.7)',
        scrollTrigger: {
          trigger: '.stats-row',
          start: 'top 85%',
          once: true,
        },
      })
    }, heroRef)

    return () => ctx.revert()
  }, [])

  // Smooth scroll helper
  const scrollTo = (id) => {
    gsap.to(window, { duration: 1, scrollTo: `#${id}`, ease: 'power2.inOut' })
  }

  return (
    <div className="bg-[#0a0e1a] text-white overflow-x-hidden" ref={heroRef}>

      {/* ── Navbar ── */}
      <nav
        ref={navRef}
        className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 sm:px-12 py-4 border-b border-white/5 bg-[#0a0e1a]/90 backdrop-blur-xl"
      >
        <span className="text-xl font-bold tracking-widest text-cyan-400 font-mono">
          EDUBOT
        </span>
        <div className="hidden sm:flex items-center gap-8 text-xs font-mono font-semibold tracking-widest text-gray-400 uppercase">
          <button onClick={() => scrollTo('features')} className="hover:text-white transition-colors">Curriculum</button>
          <button onClick={() => scrollTo('features')} className="hover:text-white transition-colors">AI Mentor</button>
          <button onClick={() => scrollTo('features')} className="hover:text-white transition-colors">Labs</button>
          <button onClick={() => scrollTo('stats')} className="hover:text-white transition-colors">Community</button>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate('/login')}
            className="hidden sm:block px-4 py-2 text-xs font-mono font-semibold tracking-widest uppercase text-white/60 hover:text-white transition-colors"
          >
            Log In
          </button>
          <button
            onClick={() => navigate('/register')}
            className="px-5 py-2 text-xs font-mono font-semibold tracking-widest uppercase border border-cyan-400 text-cyan-400 rounded-sm hover:bg-cyan-400 hover:text-gray-900 transition-all duration-300"
          >
            Initialize
          </button>
        </div>
      </nav>

      {/* ── Hero ── */}
      <section className="relative min-h-screen flex items-center pt-20 overflow-hidden">
        {/* Dark gradient background */}
        <div className="absolute inset-0 bg-gradient-to-br from-[#0a0e27] via-[#0f1629] to-[#0a1628]" />

        {/* Grid overlay */}
        <div
          className="absolute inset-0 opacity-[0.02]"
          style={{
            backgroundImage: 'linear-gradient(rgba(0,255,255,0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(0,255,255,0.1) 1px, transparent 1px)',
            backgroundSize: '50px 50px',
          }}
        />

        <div className="relative z-10 max-w-7xl mx-auto px-6 w-full grid lg:grid-cols-2 gap-12 items-center">
          {/* Left: Text Content */}
          <div>
            <div className="hero-line inline-flex items-center gap-2 px-3 py-1.5 rounded-md border border-cyan-500/30 bg-cyan-500/5 text-cyan-400 text-xs font-mono font-medium mb-6 uppercase tracking-wider">
              <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse" />
              System Architecture: MERN + Gemini AI Core
            </div>

            <h1 className="hero-line text-5xl sm:text-6xl lg:text-7xl font-extrabold leading-[1.05] tracking-tight mb-6">
              The Future of{' '}
              <span className="text-cyan-400">CS Learning</span>
              <br />
              is Here.
            </h1>

            <p className="hero-line text-base sm:text-lg text-gray-400 max-w-xl mb-10 leading-relaxed">
              Master computer science with EduBot's AI-driven ecosystem—quizzes, code analysis, and networking simulations in one powerful platform.
            </p>

            <div className="hero-line flex flex-col sm:flex-row gap-4 mb-12">
              <button
                onClick={() => navigate('/register')}
                className="group px-8 py-3.5 text-base font-semibold bg-cyan-400 text-gray-900 rounded-md hover:bg-cyan-300 transition-all duration-300 shadow-lg shadow-cyan-400/25"
              >
                Initialize Your Journey
              </button>
              <button
                onClick={() => scrollTo('features')}
                className="px-8 py-3.5 text-base font-semibold border border-gray-700 text-gray-300 rounded-md hover:bg-gray-800/50 hover:border-gray-600 transition-all duration-300"
              >
                Explore Modules
              </button>
            </div>

            {/* Tech badges */}
            <div className="hero-line flex flex-wrap gap-3 text-xs font-mono">
              <div className="flex items-center gap-2 px-3 py-2 rounded-md bg-gray-800/50 border border-gray-700/50 text-gray-400">
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400" />
                NEURAL NETS
              </div>
              <div className="flex items-center gap-2 px-3 py-2 rounded-md bg-gray-800/50 border border-gray-700/50 text-gray-400">
                <span className="w-1.5 h-1.5 rounded-full bg-blue-400" />
                PYTHON 3.0
              </div>
              <div className="flex items-center gap-2 px-3 py-2 rounded-md bg-gray-800/50 border border-gray-700/50 text-gray-400">
                <span className="w-1.5 h-1.5 rounded-full bg-purple-400" />
                KERNEL OPS
              </div>
            </div>
          </div>

          {/* Right: Brain Hologram Visualization */}
          <div className="relative hidden lg:flex items-center justify-center">
            {/* Main hologram container */}
            <div className="relative w-[500px] h-[500px]">
              {/* Outer rotating ring */}
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ duration: 20, repeat: Infinity, ease: 'linear' }}
                className="absolute inset-0 rounded-full border border-cyan-500/20"
                style={{
                  background: 'radial-gradient(circle, rgba(6,182,212,0.03) 0%, transparent 70%)',
                }}
              />

              {/* Middle ring */}
              <motion.div
                animate={{ rotate: -360 }}
                transition={{ duration: 30, repeat: Infinity, ease: 'linear' }}
                className="absolute inset-8 rounded-full border border-cyan-500/10"
              />

              {/* Brain hologram card */}
              <motion.div
                animate={{ y: [-10, 10, -10] }}
                transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
                className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-72 h-80 rounded-2xl border border-cyan-500/30 bg-gradient-to-b from-gray-900/80 to-gray-950/80 backdrop-blur-xl p-6 shadow-2xl shadow-cyan-500/20"
              >
                {/* Brain icon/illustration */}
                <div className="relative w-full h-48 mb-4 flex items-center justify-center">
                  <div className="text-8xl opacity-80">🧠</div>
                  <div className="absolute inset-0 bg-gradient-to-t from-cyan-500/20 to-transparent rounded-xl" />
                </div>

                {/* Label */}
                <div className="text-center">
                  <div className="text-cyan-400 font-mono text-xs uppercase tracking-wider mb-1">AI Core Active</div>
                  <div className="text-gray-500 text-xs font-mono">Neural Processing Online</div>
                </div>
              </motion.div>

              {/* Floating code snippet - top right */}
              <motion.div
                animate={{ y: [-5, 5, -5], rotate: [-2, 2, -2] }}
                transition={{ duration: 3, repeat: Infinity, ease: 'easeInOut', delay: 0.5 }}
                className="absolute top-8 right-0 px-4 py-3 rounded-lg border border-cyan-500/20 bg-gray-900/90 backdrop-blur-sm shadow-lg text-xs font-mono text-cyan-400"
              >
                <div className="flex items-center gap-2 mb-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-cyan-400" />
                  <span className="text-gray-500">ALGO_QUIZ</span>
                </div>
                <div className="text-gray-400">
                  <span className="text-purple-400">if</span> score <span className="text-cyan-400">&gt;</span> <span className="text-green-400">90</span>:
                </div>
              </motion.div>

              {/* Floating code snippet - bottom left */}
              <motion.div
                animate={{ y: [5, -5, 5], rotate: [2, -2, 2] }}
                transition={{ duration: 3.5, repeat: Infinity, ease: 'easeInOut', delay: 1 }}
                className="absolute bottom-16 left-0 px-4 py-3 rounded-lg border border-cyan-500/20 bg-gray-900/90 backdrop-blur-sm shadow-lg text-xs font-mono text-cyan-400"
              >
                <div className="flex items-center gap-2 mb-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-blue-400" />
                  <span className="text-gray-500">NODE_ANALYSIS</span>
                </div>
                <div className="text-gray-400">
                  func analyze(data) {'{'}<br />
                  <span className="ml-2 text-cyan-400">return</span> <span className="text-green-400">true</span>
                </div>
              </motion.div>

              {/* Glowing particles */}
              <motion.div
                animate={{ scale: [1, 1.2, 1], opacity: [0.3, 0.6, 0.3] }}
                transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                className="absolute top-1/4 right-1/4 w-2 h-2 rounded-full bg-cyan-400 blur-sm"
              />
              <motion.div
                animate={{ scale: [1, 1.3, 1], opacity: [0.4, 0.7, 0.4] }}
                transition={{ duration: 2.5, repeat: Infinity, ease: 'easeInOut', delay: 0.5 }}
                className="absolute bottom-1/3 left-1/4 w-2 h-2 rounded-full bg-blue-400 blur-sm"
              />
              <motion.div
                animate={{ scale: [1, 1.1, 1], opacity: [0.3, 0.5, 0.3] }}
                transition={{ duration: 3, repeat: Infinity, ease: 'easeInOut', delay: 1 }}
                className="absolute top-1/2 right-1/3 w-2 h-2 rounded-full bg-purple-400 blur-sm"
              />
            </div>
          </div>
        </div>

        {/* Scroll indicator */}
        <div className="absolute bottom-10 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 text-gray-600 text-xs">
          <span>Scroll</span>
          <motion.div
            animate={{ y: [0, 8, 0] }}
            transition={{ duration: 1.5, repeat: Infinity, ease: 'easeInOut' }}
            className="w-px h-8 bg-gradient-to-b from-cyan-500/30 to-transparent"
          />
        </div>
      </section>

      {/* ── Stats ── */}
      <section id="stats" className="py-20 border-y border-white/5 bg-white/[0.02]">
        <div className="stats-row max-w-4xl mx-auto px-6 grid grid-cols-2 sm:grid-cols-4 gap-8 text-center">
          {stats.map(({ value, label }) => (
            <div key={label} className="stat-item">
              <div className="text-4xl font-extrabold bg-gradient-to-r from-blue-400 to-violet-400 bg-clip-text text-transparent mb-1">
                {value}
              </div>
              <div className="text-sm text-white/40 uppercase tracking-widest">{label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Features ── */}
      <section id="features" className="py-28 px-6">
        <div className="max-w-7xl mx-auto">
          <FadeUp className="text-center mb-20">
            <p className="text-sm text-blue-400 uppercase tracking-widest font-semibold mb-3">What's inside</p>
            <h2 className="text-4xl sm:text-5xl font-bold mb-4">Everything you need to excel</h2>
            <p className="text-white/40 text-lg max-w-xl mx-auto">Six powerful tools, one seamless platform.</p>
          </FadeUp>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map(({ icon, title, description, color, glow }, i) => (
              <FadeUp key={title} delay={i * 0.08}>
                <motion.div
                  whileHover={{ y: -6, scale: 1.02 }}
                  transition={{ type: 'spring', stiffness: 300, damping: 20 }}
                  className={`relative group rounded-2xl border border-white/5 bg-white/[0.03] p-7 hover:border-white/10 hover:bg-white/[0.06] transition-colors duration-300 overflow-hidden`}
                >
                  {/* Glow on hover */}
                  <div className={`absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500 bg-gradient-to-br ${color} blur-2xl scale-150 -z-10`} style={{ opacity: 0 }}
                    onMouseEnter={e => e.currentTarget.style.opacity = '0.07'}
                    onMouseLeave={e => e.currentTarget.style.opacity = '0'}
                  />

                  <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${color} flex items-center justify-center text-2xl mb-5 shadow-lg`}>
                    {icon}
                  </div>
                  <h3 className="text-lg font-semibold text-white mb-2">{title}</h3>
                  <p className="text-white/45 text-sm leading-relaxed">{description}</p>
                </motion.div>
              </FadeUp>
            ))}
          </div>
        </div>
      </section>

      {/* ── How it works ── */}
      <section className="py-28 px-6 bg-white/[0.02] border-y border-white/5">
        <div className="max-w-4xl mx-auto">
          <FadeUp className="text-center mb-16">
            <p className="text-sm text-violet-400 uppercase tracking-widest font-semibold mb-3">Simple flow</p>
            <h2 className="text-4xl sm:text-5xl font-bold">How EduBot works</h2>
          </FadeUp>

          <div className="relative">
            {/* Vertical line */}
            <div className="absolute left-6 sm:left-1/2 top-0 bottom-0 w-px bg-gradient-to-b from-blue-500/50 via-violet-500/50 to-transparent -translate-x-1/2" />

            {[
              { step: '01', title: 'Pick a subject', desc: 'Choose from Computer Networks, DBMS, Python, Java, C++, or C.' },
              { step: '02', title: 'Practice with AI', desc: 'Get AI-generated questions, run code, simulate networks, or speak aloud.' },
              { step: '03', title: 'Get instant feedback', desc: 'Gemini AI scores your work, explains mistakes, and suggests improvements.' },
              { step: '04', title: 'Track your growth', desc: 'Watch your accuracy, streak, and points climb on your personal dashboard.' },
            ].map(({ step, title, desc }, i) => (
              <FadeUp key={step} delay={i * 0.1} className={`relative flex gap-8 mb-12 ${i % 2 === 0 ? 'sm:flex-row' : 'sm:flex-row-reverse'} items-start sm:items-center`}>
                <div className={`flex-1 ${i % 2 === 0 ? 'sm:text-right' : 'sm:text-left'} pl-16 sm:pl-0`}>
                  <div className="text-xs text-white/30 uppercase tracking-widest mb-1">{step}</div>
                  <h3 className="text-xl font-semibold mb-2">{title}</h3>
                  <p className="text-white/45 text-sm leading-relaxed">{desc}</p>
                </div>
                <div className="absolute left-0 sm:relative sm:left-auto flex-shrink-0 w-12 h-12 rounded-full bg-gradient-to-br from-blue-500 to-violet-500 flex items-center justify-center font-bold text-sm shadow-lg shadow-blue-500/30 sm:mx-0">
                  {i + 1}
                </div>
                <div className="flex-1 hidden sm:block" />
              </FadeUp>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ── */}
      <section id="cta" className="py-32 px-6 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-600/10 via-violet-600/10 to-transparent" />
        <div className="orb-1 absolute top-0 left-1/2 w-[600px] h-[600px] bg-blue-600/10 rounded-full blur-3xl -translate-x-1/2 pointer-events-none" />

        <FadeUp className="relative z-10 max-w-2xl mx-auto text-center">
          <h2 className="text-4xl sm:text-5xl font-extrabold mb-6 leading-tight">
            Ready to level up
            <br />
            <span className="bg-gradient-to-r from-blue-400 to-violet-400 bg-clip-text text-transparent">
              your CS skills?
            </span>
          </h2>
          <p className="text-white/45 text-lg mb-10">
            Join students already using EduBot to practice smarter. Free to get started.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.97 }}
              onClick={() => navigate('/register')}
              className="px-10 py-4 text-base font-semibold bg-gradient-to-r from-blue-500 to-violet-500 rounded-xl shadow-2xl shadow-blue-500/30 hover:shadow-blue-500/50 transition-shadow"
            >
              Sign Up Free
            </motion.button>
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.97 }}
              onClick={() => navigate('/login')}
              className="px-10 py-4 text-base font-semibold border border-white/10 rounded-xl hover:bg-white/5 transition-colors"
            >
              Log In
            </motion.button>
          </div>
        </FadeUp>
      </section>

      {/* ── Footer ── */}
      <footer className="border-t border-white/5 py-10 px-6 text-center text-white/25 text-sm">
        <p>© {new Date().getFullYear()} EduBot Learning Platform · Pillai College of Engineering</p>
      </footer>
    </div>
  )
}
