import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion, useInView, useAnimation, AnimatePresence } from 'framer-motion'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { ScrollToPlugin } from 'gsap/ScrollToPlugin'

gsap.registerPlugin(ScrollTrigger, ScrollToPlugin)

/* ── Typewriter hook ── */
function useTypewriter(words, speed = 80, pause = 1800) {
  const [display, setDisplay] = useState('')
  const [wIdx, setWIdx] = useState(0)
  const [typing, setTyping] = useState(true)
  useEffect(() => {
    const word = words[wIdx]
    if (typing) {
      if (display.length < word.length) {
        const t = setTimeout(() => setDisplay(word.slice(0, display.length + 1)), speed)
        return () => clearTimeout(t)
      } else {
        const t = setTimeout(() => setTyping(false), pause)
        return () => clearTimeout(t)
      }
    } else {
      if (display.length > 0) {
        const t = setTimeout(() => setDisplay(display.slice(0, -1)), speed / 2)
        return () => clearTimeout(t)
      } else {
        setWIdx((wIdx + 1) % words.length)
        setTyping(true)
      }
    }
  }, [display, typing, wIdx])
  return display
}

/* ── Scroll reveal ── */
function Reveal({ children, delay = 0, x = 0, y = 40 }) {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-60px' })
  return (
    <motion.div ref={ref}
      initial={{ opacity: 0, x, y }}
      animate={inView ? { opacity: 1, x: 0, y: 0 } : {}}
      transition={{ duration: 0.7, delay, ease: [0.22, 1, 0.36, 1] }}>
      {children}
    </motion.div>
  )
}

/* ── Window chrome (fake OS title bar) ── */
function WindowCard({ title, tag, icon, children, accent = '#22d3ee', className = '' }) {
  return (
    <div className={`rounded-xl overflow-hidden ${className}`}
      style={{
        background: 'linear-gradient(160deg, rgba(255,255,255,0.06) 0%, rgba(255,255,255,0.02) 100%)',
        backdropFilter: 'blur(20px)',
        border: '1px solid rgba(255,255,255,0.08)',
        boxShadow: '0 8px 32px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.10)',
      }}>
      {/* Title bar */}
      <div className="flex items-center gap-2 px-4 py-2.5 border-b border-white/5"
        style={{ background: 'rgba(0,0,0,0.25)' }}>
        <div className="flex gap-1.5">
          <div className="w-2.5 h-2.5 rounded-full bg-red-500/70" />
          <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/70" />
          <div className="w-2.5 h-2.5 rounded-full bg-green-500/70" />
        </div>
        <span className="ml-2 text-[10px] font-mono text-white/30 uppercase tracking-widest flex-1 text-center">{title}</span>
        <span className="text-[9px] font-mono px-1.5 py-0.5 rounded" style={{ background: accent + '22', color: accent, border: '1px solid ' + accent + '44' }}>{tag}</span>
      </div>
      <div className="p-4">
        <div className="text-2xl mb-2.5">{icon}</div>
        {children}
      </div>
    </div>
  )
}

/* ── Terminal line ── */
function TermLine({ prompt = '$', cmd, out, delay = 0 }) {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true })
  return (
    <motion.div ref={ref} initial={{ opacity: 0 }} animate={inView ? { opacity: 1 } : {}} transition={{ delay }}
      className="font-mono text-xs leading-relaxed">
      <div><span className="text-cyan-400">{prompt}</span> <span className="text-white/80">{cmd}</span></div>
      {out && <div className="text-white/35 ml-4">{out}</div>}
    </motion.div>
  )
}

const navLinks = [
  { id: 'modules', label: 'Modules' },
  { id: 'how',     label: 'Process' },
  { id: 'stack',   label: 'Stack' },
  { id: 'compare', label: 'Compare' },
]

const modules = [
  { title: 'ai-quiz.exe',       tag: 'GEMINI',   icon: '🤖', accent: '#a78bfa', desc: 'Adaptive MCQs generated by Gemini AI across six CS subjects, tuned to your level in real time.' },
  { title: 'code-runner.sh',    tag: 'DOCKER',   icon: '💻', accent: '#22d3ee', desc: 'Write and run Python, Java, C++, and C in-browser with Docker execution and instant AI feedback.' },
  { title: 'net-sim.app',       tag: 'CANVAS',   icon: '🌐', accent: '#10b981', desc: 'Drag-and-drop routers, switches, and PCs onto a canvas. AI evaluates your IP configuration.' },
  { title: 'sql-lab.db',        tag: 'SQLITE',   icon: '🗄️', accent: '#f59e0b', desc: 'Run live queries against a real SQLite database and get scored with AI-suggested corrections.' },
  { title: 'fluency.wav',       tag: 'WHISPER',  icon: '🗣️', accent: '#f472b6', desc: 'Record a spoken response. Whisper + CRNN + Gemini score your grammar, pace, fillers, and pitch.' },
  { title: 'syllabus.json',     tag: 'BROWSE',   icon: '📚', accent: '#6366f1', desc: 'Structured syllabi for every subject so you always know exactly what to study next.' },
]

const stack = [
  { name: 'React 18',    v: 'v18.2', color: '#61dafb' },
  { name: 'Node.js',     v: 'v20',   color: '#68a063' },
  { name: 'MongoDB',     v: 'v7',    color: '#47a248' },
  { name: 'Gemini AI',   v: '2.5',   color: '#4285f4' },
  { name: 'FastAPI',     v: '0.11',  color: '#009688' },
  { name: 'Whisper',     v: 'tiny',  color: '#f59e0b' },
  { name: 'Docker',      v: '24',    color: '#2496ed' },
  { name: 'JWT',         v: 'RS256', color: '#a78bfa' },
]

export default function LandingPage() {
  const navigate   = useNavigate()
  const heroRef    = useRef(null)
  const navRef     = useRef(null)
  const [menuOpen, setMenuOpen]   = useState(false)
  const [active,   setActive]     = useState('')
  const typed = useTypewriter(['CS Learning', 'Code Mastery', 'Network Design', 'SQL Fluency', 'AI Practice'], 75, 1600)

  useEffect(() => {
    const ctx = gsap.context(() => {
      // Scan-line flicker on hero
      gsap.to('.scan-line', { opacity: 0.04, duration: 0.08, repeat: -1, yoyo: true, ease: 'none' })
      // Orb drift
      gsap.to('.orb-a', { x: 40, y: -30, duration: 9, repeat: -1, yoyo: true, ease: 'sine.inOut' })
      gsap.to('.orb-b', { x: -30, y: 40, duration: 11, repeat: -1, yoyo: true, ease: 'sine.inOut', delay: 2 })
      gsap.to('.orb-c', { x: 20, y: 20, duration: 7, repeat: -1, yoyo: true, ease: 'sine.inOut', delay: 4 })
      // Nav active tracking
      navLinks.forEach(({ id }) => {
        ScrollTrigger.create({
          trigger: '#' + id,
          start: 'top 55%', end: 'bottom 55%',
          onEnter: () => setActive(id),
          onEnterBack: () => setActive(id),
        })
      })
    }, heroRef)
    return () => ctx.revert()
  }, [])

  const scrollTo = id => { gsap.to(window, { duration: 1, scrollTo: '#' + id, ease: 'power2.inOut' }); setMenuOpen(false) }

  const glass = {
    background: 'linear-gradient(135deg, rgba(255,255,255,0.07) 0%, rgba(255,255,255,0.02) 100%)',
    backdropFilter: 'blur(24px) saturate(180%)',
    WebkitBackdropFilter: 'blur(24px) saturate(180%)',
    border: '1px solid rgba(255,255,255,0.09)',
    boxShadow: '0 4px 32px rgba(0,0,0,0.35), inset 0 1px 0 rgba(255,255,255,0.10)',
  }

  return (
    <div ref={heroRef} style={{ background: 'linear-gradient(180deg,#050810 0%,#0a0e1a 30%,#0a0e1a 70%,#000 100%)', color: '#fff', overflowX: 'hidden', fontFamily: "'Inter','Segoe UI',sans-serif" }}>

      {/* ── Navbar ── */}
      <nav ref={navRef} className="fixed top-0 left-0 right-0 z-50" style={glass}>
        <div className="flex items-center justify-between px-6 sm:px-12 py-3.5">
          <button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
            className="flex items-center gap-2 group">
            <div className="w-7 h-7 rounded-md flex items-center justify-center text-xs font-black"
              style={{ background: 'linear-gradient(135deg,#06b6d4,#8b5cf6)', boxShadow: '0 0 14px rgba(6,182,212,0.4)' }}>E</div>
            <span className="text-sm font-bold tracking-widest text-white font-mono group-hover:text-cyan-400 transition-colors">EDUBOT</span>
          </button>

          <div className="hidden sm:flex items-center gap-1 rounded-full px-2 py-1.5" style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.07)' }}>
            {navLinks.map(({ id, label }) => (
              <button key={id} onClick={() => scrollTo(id)}
                className="relative px-4 py-1.5 rounded-full text-xs font-mono font-semibold tracking-wider uppercase transition-all duration-300"
                style={{ color: active === id ? '#0f172a' : 'rgba(156,163,175,0.9)', background: active === id ? '#22d3ee' : 'transparent' }}>
                {label}
              </button>
            ))}
          </div>

          <div className="flex items-center gap-2">
            <button onClick={() => navigate('/login')}
              className="hidden sm:block px-4 py-1.5 text-xs font-mono font-semibold tracking-wider uppercase text-white/50 hover:text-white transition-colors rounded-full hover:bg-white/5">
              Login
            </button>
            <button onClick={() => navigate('/register')}
              className="px-4 py-1.5 text-xs font-mono font-bold tracking-wider uppercase rounded-full transition-all duration-300"
              style={{ background: 'linear-gradient(135deg,#06b6d4,#8b5cf6)', boxShadow: '0 0 16px rgba(6,182,212,0.3)' }}>
              Start Free
            </button>
            <button onClick={() => setMenuOpen(o => !o)} className="sm:hidden p-2 rounded-lg hover:bg-white/5 transition-colors">
              <div className="space-y-1.5">
                <span className={`block w-5 h-0.5 bg-gray-400 transition-all ${menuOpen ? 'rotate-45 translate-y-2' : ''}`} />
                <span className={`block w-5 h-0.5 bg-gray-400 transition-all ${menuOpen ? 'opacity-0' : ''}`} />
                <span className={`block w-5 h-0.5 bg-gray-400 transition-all ${menuOpen ? '-rotate-45 -translate-y-2' : ''}`} />
              </div>
            </button>
          </div>
        </div>
        <AnimatePresence>
          {menuOpen && (
            <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}
              className="sm:hidden overflow-hidden border-t border-white/5 px-6 pb-4 flex flex-col gap-1 pt-3">
              {navLinks.map(({ id, label }) => (
                <button key={id} onClick={() => scrollTo(id)}
                  className="text-left py-2 text-xs font-mono font-semibold tracking-widest uppercase transition-colors"
                  style={{ color: active === id ? '#22d3ee' : 'rgba(156,163,175,0.8)' }}>{label}</button>
              ))}
              <div className="flex gap-2 pt-2 border-t border-white/5 mt-1">
                <button onClick={() => navigate('/login')} className="flex-1 py-2 text-xs font-mono text-center text-white/50 hover:text-white transition-colors">Login</button>
                <button onClick={() => navigate('/register')} className="flex-1 py-2 text-xs font-mono font-bold text-center rounded-full" style={{ background: 'linear-gradient(135deg,#06b6d4,#8b5cf6)' }}>Start Free</button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </nav>

      {/* ── HERO — Terminal OS style ── */}
      <section className="relative min-h-[90vh] flex items-center pt-20 pb-10 overflow-hidden">
        {/* Scan lines */}
        <div className="scan-line absolute inset-0 pointer-events-none" style={{ backgroundImage: 'repeating-linear-gradient(0deg,transparent,transparent 2px,rgba(0,255,255,0.015) 2px,rgba(0,255,255,0.015) 4px)', zIndex: 1 }} />
        {/* Orbs */}
        <div className="orb-a absolute top-1/4 left-1/5 w-96 h-96 rounded-full pointer-events-none" style={{ background: 'radial-gradient(circle,rgba(6,182,212,0.12) 0%,transparent 70%)', filter: 'blur(40px)' }} />
        <div className="orb-b absolute bottom-1/4 right-1/5 w-80 h-80 rounded-full pointer-events-none" style={{ background: 'radial-gradient(circle,rgba(139,92,246,0.10) 0%,transparent 70%)', filter: 'blur(40px)' }} />
        <div className="orb-c absolute top-1/2 left-1/2 w-64 h-64 rounded-full pointer-events-none" style={{ background: 'radial-gradient(circle,rgba(16,185,129,0.06) 0%,transparent 70%)', filter: 'blur(40px)' }} />
        {/* Grid */}
        <div className="absolute inset-0 pointer-events-none" style={{ backgroundImage: 'linear-gradient(rgba(6,182,212,0.03) 1px,transparent 1px),linear-gradient(90deg,rgba(6,182,212,0.03) 1px,transparent 1px)', backgroundSize: '60px 60px' }} />

        <div className="relative z-10 max-w-7xl mx-auto px-6 w-full">
          <div className="grid lg:grid-cols-2 gap-10 items-center">

            {/* Left — big type */}
            <div>
              {/* Status pill */}
              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
                className="inline-flex items-center gap-2 px-3 py-1 rounded-full mb-5 text-xs font-mono"
                style={{ background: 'rgba(6,182,212,0.08)', border: '1px solid rgba(6,182,212,0.2)' }}>
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse" />
                <span className="text-cyan-400 tracking-widest uppercase">System Online · MERN + Gemini AI</span>
              </motion.div>

              <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
                <div className="text-white/20 font-mono text-xs mb-1.5 tracking-widest">// initializing</div>
                <h1 className="font-black leading-[0.95] tracking-tight mb-1.5" style={{ fontSize: 'clamp(2rem,5vw,3.5rem)' }}>
                  The Future
                </h1>
                <h1 className="font-black leading-[0.95] tracking-tight mb-1.5" style={{ fontSize: 'clamp(2rem,5vw,3.5rem)', background: 'linear-gradient(90deg,#22d3ee,#a78bfa)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
                  of {typed}<span className="animate-pulse" style={{ WebkitTextFillColor: '#22d3ee' }}>_</span>
                </h1>
                <h1 className="font-black leading-[0.95] tracking-tight" style={{ fontSize: 'clamp(2rem,5vw,3.5rem)' }}>
                  is Here.
                </h1>
              </motion.div>

              <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.5 }}
                className="text-white/45 text-sm leading-relaxed mt-5 mb-6 max-w-lg">
                One AI-powered platform for quizzes, code execution, networking simulations, SQL practice, and English fluency — built for CS students.
              </motion.p>

              <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.65 }}
                className="flex flex-wrap gap-3">
                <button onClick={() => navigate('/register')}
                  className="px-6 py-2.5 font-bold text-sm rounded-xl text-gray-900 transition-all duration-300 hover:scale-105"
                  style={{ background: 'linear-gradient(135deg,#22d3ee,#8b5cf6)', boxShadow: '0 0 24px rgba(6,182,212,0.3)' }}>
                  Initialize Your Journey →
                </button>
                <button onClick={() => scrollTo('modules')}
                  className="px-6 py-2.5 font-semibold text-sm rounded-xl text-white/70 hover:text-white transition-all duration-300 hover:bg-white/5"
                  style={{ border: '1px solid rgba(255,255,255,0.12)' }}>
                  Explore Modules
                </button>
              </motion.div>

              {/* Mini stats row */}
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.85 }}
                className="flex gap-6 mt-8 pt-6" style={{ borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                {[['6', 'Subjects'], ['5+', 'AI Tools'], ['4', 'Languages'], ['∞', 'Questions']].map(([v, l]) => (
                  <div key={l}>
                    <div className="text-xl font-black font-mono" style={{ background: 'linear-gradient(90deg,#22d3ee,#a78bfa)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>{v}</div>
                    <div className="text-[10px] text-white/30 uppercase tracking-widest font-mono">{l}</div>
                  </div>
                ))}
              </motion.div>
            </div>

            {/* Right — floating icons + terminal */}
            <motion.div initial={{ opacity: 0, x: 40 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.4, duration: 0.8 }}
              className="hidden lg:flex flex-col gap-5">

              {/* ── Floating icon visualization ── */}
              <div className="relative flex items-center justify-center h-52">
                {/* Outer rotating ring */}
                <div className="ring-outer absolute w-44 h-44 rounded-full"
                  style={{ border: '1px solid rgba(6,182,212,0.18)', background: 'radial-gradient(circle,rgba(6,182,212,0.04) 0%,transparent 70%)' }} />
                {/* Inner counter-rotating ring */}
                <div className="ring-inner absolute w-28 h-28 rounded-full"
                  style={{ border: '1px solid rgba(139,92,246,0.15)' }} />

                {/* Center: two icon circles side by side */}
                <motion.div animate={{ y: [-6, 6, -6] }} transition={{ duration: 3.5, repeat: Infinity, ease: 'easeInOut' }}
                  className="relative z-10 flex items-center gap-4">
                  {/* Laptop circle */}
                  <div className="w-14 h-14 rounded-full flex items-center justify-center"
                    style={{ background: 'linear-gradient(145deg,rgba(6,182,212,0.15),rgba(6,182,212,0.05))', border: '2px solid rgba(6,182,212,0.35)', boxShadow: '0 0 20px rgba(6,182,212,0.2), inset 0 1px 0 rgba(255,255,255,0.12)' }}>
                    <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#22d3ee" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                      <rect x="2" y="3" width="20" height="14" rx="2"/>
                      <line x1="8" y1="21" x2="16" y2="21"/>
                      <line x1="12" y1="17" x2="12" y2="21"/>
                    </svg>
                  </div>
                  {/* CPU circle */}
                  <div className="w-14 h-14 rounded-full flex items-center justify-center"
                    style={{ background: 'linear-gradient(145deg,rgba(139,92,246,0.15),rgba(139,92,246,0.05))', border: '2px solid rgba(139,92,246,0.35)', boxShadow: '0 0 20px rgba(139,92,246,0.2), inset 0 1px 0 rgba(255,255,255,0.12)' }}>
                    <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#a78bfa" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                      <rect x="4" y="4" width="16" height="16" rx="2"/>
                      <rect x="9" y="9" width="6" height="6"/>
                      <line x1="9" y1="2" x2="9" y2="4"/><line x1="15" y1="2" x2="15" y2="4"/>
                      <line x1="9" y1="20" x2="9" y2="22"/><line x1="15" y1="20" x2="15" y2="22"/>
                      <line x1="20" y1="9" x2="22" y2="9"/><line x1="20" y1="14" x2="22" y2="14"/>
                      <line x1="2" y1="9" x2="4" y2="9"/><line x1="2" y1="14" x2="4" y2="14"/>
                    </svg>
                  </div>
                </motion.div>

                {/* Glowing particles */}
                {[['top-6','left-1/3','#22d3ee',2],[' bottom-6','right-1/3','#a78bfa',2.5],['top-1/2','right-6','#10b981',1.8]].map(([t,l,c,d],i) => (
                  <motion.div key={i} className="absolute w-1.5 h-1.5 rounded-full" style={{ top: t.includes('top') ? t.replace('top-','') : undefined, bottom: t.includes('bottom') ? t.replace(' bottom-','') : undefined, left: l.includes('left') ? undefined : undefined, right: l.includes('right') ? undefined : undefined, background: c, boxShadow: '0 0 8px ' + c, [t.split('-')[0]]: t.split('-')[1], [l.split('-')[0]]: l.split('-')[1] }}
                    animate={{ scale: [1, 1.6, 1], opacity: [0.4, 0.9, 0.4] }}
                    transition={{ duration: d, repeat: Infinity, ease: 'easeInOut', delay: i * 0.4 }} />
                ))}
              </div>

              {/* ── Terminal window ── */}
              <div className="rounded-xl overflow-hidden" style={{ ...glass, boxShadow: '0 16px 48px rgba(6,182,212,0.10), 0 4px 16px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.10)' }}>
                <div className="flex items-center gap-2 px-4 py-2.5 border-b border-white/5" style={{ background: 'rgba(0,0,0,0.3)' }}>
                  <div className="flex gap-1.5">
                    <div className="w-2.5 h-2.5 rounded-full bg-red-500/80" />
                    <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/80" />
                    <div className="w-2.5 h-2.5 rounded-full bg-green-500/80" />
                  </div>
                  <span className="ml-2 text-[10px] font-mono text-white/25 tracking-widest">edubot — terminal</span>
                </div>
                <div className="p-4 space-y-2" style={{ background: 'rgba(0,0,0,0.2)' }}>
                  <TermLine prompt=">" cmd="edubot init --subject=all" out="✓ Loading 6 subjects..." delay={0.6} />
                  <TermLine prompt=">" cmd="edubot quiz --ai=gemini --level=adaptive" out="✓ Generating 10 questions..." delay={0.9} />
                  <TermLine prompt=">" cmd="edubot run --lang=python --docker=true" out="✓ Container ready · exec time 0.3s" delay={1.2} />
                  <TermLine prompt=">" cmd="edubot network --sim=true --eval=ai" out="✓ Canvas initialized · AI evaluator online" delay={1.5} />
                  <TermLine prompt=">" cmd="edubot score --user=you" out="✓ Level 4 · 840 pts · 7-day streak 🔥" delay={1.8} />
                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 2.2 }}
                    className="flex items-center gap-2 font-mono text-xs pt-1">
                    <span className="text-cyan-400">›</span>
                    <span className="text-white/40">All systems operational.</span>
                    <span className="w-1.5 h-3.5 bg-cyan-400 animate-pulse ml-1" style={{ borderRadius: 1 }} />
                  </motion.div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>

        {/* Scroll cue */}
        <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2">
          <motion.div animate={{ y: [0, 8, 0] }} transition={{ duration: 1.6, repeat: Infinity }}
            className="w-px h-10 rounded-full" style={{ background: 'linear-gradient(180deg,rgba(34,211,238,0.5),transparent)' }} />
        </div>
      </section>

      {/* ── MODULES — Bento grid with window chrome ── */}
      <section id="modules" className="py-20 px-4 sm:px-6 mt-4">
        <div className="max-w-6xl mx-auto">
          <Reveal>
            <div className="flex items-end justify-between mb-10 flex-wrap gap-4">
              <div>
                <div className="text-xs font-mono text-cyan-400 uppercase tracking-widest mb-1.5">// modules</div>
                <h2 className="text-3xl sm:text-4xl font-black leading-tight">Six tools.<br /><span style={{ background: 'linear-gradient(90deg,#22d3ee,#a78bfa)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>One platform.</span></h2>
              </div>
              <div className="text-white/30 text-xs font-mono max-w-xs text-right hidden sm:block">
                Each module is a standalone AI-powered learning environment.
              </div>
            </div>
          </Reveal>

          {/* Bento: 3-col, rows vary */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Row 1: wide + narrow */}
            <Reveal delay={0} x={-20} y={0} className="md:col-span-2">
              <motion.div whileHover={{ scale: 1.01 }} transition={{ type: 'spring', stiffness: 300, damping: 25 }}>
                <WindowCard title={modules[0].title} tag={modules[0].tag} icon={modules[0].icon} accent={modules[0].accent}>
                  <h3 className="text-lg font-bold text-white mb-2">AI Quizzes</h3>
                  <p className="text-white/45 text-sm leading-relaxed mb-4">{modules[0].desc}</p>
                  <div className="flex gap-2 flex-wrap">
                    {['MCQ','Adaptive','Gemini 2.5','6 Subjects'].map(t => (
                      <span key={t} className="text-[10px] font-mono px-2 py-1 rounded-md" style={{ background: modules[0].accent + '15', color: modules[0].accent, border: '1px solid ' + modules[0].accent + '30' }}>{t}</span>
                    ))}
                  </div>
                </WindowCard>
              </motion.div>
            </Reveal>

            <Reveal delay={0.08} x={20} y={0}>
              <motion.div whileHover={{ scale: 1.02 }} transition={{ type: 'spring', stiffness: 300, damping: 25 }} className="h-full">
                <WindowCard title={modules[5].title} tag={modules[5].tag} icon={modules[5].icon} accent={modules[5].accent} className="h-full">
                  <h3 className="text-lg font-bold text-white mb-2">Syllabus Browser</h3>
                  <p className="text-white/45 text-sm leading-relaxed">{modules[5].desc}</p>
                </WindowCard>
              </motion.div>
            </Reveal>

            {/* Row 2: narrow + wide */}
            <Reveal delay={0.12} x={-20} y={0}>
              <motion.div whileHover={{ scale: 1.02 }} transition={{ type: 'spring', stiffness: 300, damping: 25 }} className="h-full">
                <WindowCard title={modules[3].title} tag={modules[3].tag} icon={modules[3].icon} accent={modules[3].accent} className="h-full">
                  <h3 className="text-lg font-bold text-white mb-2">SQL Practice</h3>
                  <p className="text-white/45 text-sm leading-relaxed">{modules[3].desc}</p>
                </WindowCard>
              </motion.div>
            </Reveal>

            <Reveal delay={0.16} x={0} y={20} className="md:col-span-2">
              <motion.div whileHover={{ scale: 1.01 }} transition={{ type: 'spring', stiffness: 300, damping: 25 }}>
                <WindowCard title={modules[1].title} tag={modules[1].tag} icon={modules[1].icon} accent={modules[1].accent}>
                  <h3 className="text-lg font-bold text-white mb-2">Code Editor</h3>
                  <p className="text-white/45 text-sm leading-relaxed mb-4">{modules[1].desc}</p>
                  <div className="rounded-lg p-3 font-mono text-xs" style={{ background: 'rgba(0,0,0,0.4)', border: '1px solid rgba(255,255,255,0.06)' }}>
                    <span className="text-violet-400">def</span> <span className="text-cyan-400">solve</span><span className="text-white/60">(n):</span><br />
                    <span className="ml-4 text-white/40">return</span> <span className="ml-1 text-green-400">n * (n+1) // 2</span>
                  </div>
                </WindowCard>
              </motion.div>
            </Reveal>

            {/* Row 3: equal thirds */}
            <Reveal delay={0.2} x={-20} y={0}>
              <motion.div whileHover={{ scale: 1.02 }} transition={{ type: 'spring', stiffness: 300, damping: 25 }} className="h-full">
                <WindowCard title={modules[2].title} tag={modules[2].tag} icon={modules[2].icon} accent={modules[2].accent} className="h-full">
                  <h3 className="text-lg font-bold text-white mb-2">Networking Playground</h3>
                  <p className="text-white/45 text-sm leading-relaxed">{modules[2].desc}</p>
                </WindowCard>
              </motion.div>
            </Reveal>

            <Reveal delay={0.24} x={0} y={20} className="md:col-span-2">
              <motion.div whileHover={{ scale: 1.01 }} transition={{ type: 'spring', stiffness: 300, damping: 25 }}>
                <WindowCard title={modules[4].title} tag={modules[4].tag} icon={modules[4].icon} accent={modules[4].accent}>
                  <h3 className="text-lg font-bold text-white mb-2">English Fluency</h3>
                  <p className="text-white/45 text-sm leading-relaxed mb-4">{modules[4].desc}</p>
                  <div className="flex items-end gap-1 h-8">
                    {[3,5,8,6,9,4,7,5,8,6,4,7].map((h, i) => (
                      <motion.div key={i} className="flex-1 rounded-sm" style={{ background: modules[4].accent + '60' }}
                        animate={{ height: [h * 3, h * 3 + 8, h * 3] }}
                        transition={{ duration: 0.6 + i * 0.05, repeat: Infinity, ease: 'easeInOut', delay: i * 0.08 }} />
                    ))}
                  </div>
                </WindowCard>
              </motion.div>
            </Reveal>
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS — horizontal timeline ── */}
      <section id="how" className="py-20 px-4 sm:px-6 mt-2" style={{ background: 'linear-gradient(180deg,transparent,rgba(6,182,212,0.03) 50%,transparent)' }}>
        <div className="max-w-5xl mx-auto">
          <Reveal className="text-center mb-12">
            <div className="text-xs font-mono text-violet-400 uppercase tracking-widest mb-1.5">// process</div>
            <h2 className="text-3xl sm:text-4xl font-black">How it <span style={{ background: 'linear-gradient(90deg,#a78bfa,#22d3ee)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>works</span></h2>
          </Reveal>

          <div className="relative">
            {/* Connecting line */}
            <div className="hidden md:block absolute top-8 left-0 right-0 h-px" style={{ background: 'linear-gradient(90deg,transparent,rgba(6,182,212,0.3) 20%,rgba(139,92,246,0.3) 80%,transparent)' }} />

            <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
              {[
                { n:'01', title:'Pick a subject',       desc:'Choose from 6 CS subjects — Networks, DBMS, Python, Java, C++, or C.', color:'#22d3ee' },
                { n:'02', title:'Practice with AI',     desc:'Get AI-generated questions, run code, simulate networks, or speak aloud.', color:'#a78bfa' },
                { n:'03', title:'Get instant feedback', desc:'Gemini AI scores your work, explains mistakes, and suggests improvements.', color:'#10b981' },
                { n:'04', title:'Track your growth',    desc:'Watch accuracy, streak, and points climb on your personal dashboard.', color:'#f59e0b' },
              ].map(({ n, title, desc, color }, i) => (
                <Reveal key={n} delay={i * 0.1} y={30}>
                  <div className="relative text-center">
                    <div className="w-16 h-16 rounded-2xl mx-auto mb-5 flex items-center justify-center text-xl font-black font-mono relative z-10"
                      style={{ background: color + '15', border: '2px solid ' + color + '40', color, boxShadow: '0 0 20px ' + color + '20' }}>
                      {n}
                    </div>
                    <h3 className="text-base font-bold text-white mb-2">{title}</h3>
                    <p className="text-white/40 text-sm leading-relaxed">{desc}</p>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── STACK — dependency list style ── */}
      <section id="stack" className="py-20 px-4 sm:px-6 mt-2">
        <div className="max-w-4xl mx-auto">
          <Reveal className="mb-10">
            <div className="text-xs font-mono text-emerald-400 uppercase tracking-widest mb-1.5">// package.json</div>
            <h2 className="text-3xl sm:text-4xl font-black">Dependencies</h2>
          </Reveal>

          <div className="rounded-2xl overflow-hidden" style={glass}>
            <div className="px-6 py-3 border-b border-white/5 flex items-center gap-3" style={{ background: 'rgba(0,0,0,0.3)' }}>
              <div className="flex gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-red-500/70" /><div className="w-2.5 h-2.5 rounded-full bg-yellow-500/70" /><div className="w-2.5 h-2.5 rounded-full bg-green-500/70" /></div>
              <span className="text-xs font-mono text-white/25 tracking-widest">package.json — edubot</span>
            </div>
            <div className="p-6 font-mono text-sm">
              <div className="text-white/25 mb-4">{'"dependencies": {'}</div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-1 ml-4">
                {stack.map(({ name, v, color }, i) => (
                  <Reveal key={name} delay={i * 0.05} x={-10} y={0}>
                    <div className="flex items-center justify-between py-1.5 px-3 rounded-lg hover:bg-white/3 transition-colors group">
                      <div className="flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full flex-shrink-0" style={{ background: color, boxShadow: '0 0 6px ' + color }} />
                        <span className="text-white/70 group-hover:text-white transition-colors">"{name}"</span>
                      </div>
                      <span className="text-white/25 text-xs">"{v}"</span>
                    </div>
                  </Reveal>
                ))}
              </div>
              <div className="text-white/25 mt-4">{'}'}</div>
            </div>
          </div>
        </div>
      </section>

      {/* ── COMPARE — side by side ── */}
      <section id="compare" className="py-20 px-4 sm:px-6 mt-2" style={{ background: 'linear-gradient(180deg,transparent,rgba(139,92,246,0.04) 50%,transparent)' }}>
        <div className="max-w-4xl mx-auto">
          <Reveal className="text-center mb-10">
            <div className="text-xs font-mono text-amber-400 uppercase tracking-widest mb-1.5">// diff --traditional vs edubot</div>
            <h2 className="text-3xl sm:text-4xl font-black">The difference</h2>
          </Reveal>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Reveal delay={0} x={-30} y={0}>
              <div className="rounded-2xl p-6 h-full" style={{ background: 'rgba(239,68,68,0.04)', border: '1px solid rgba(239,68,68,0.12)', boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.04)' }}>
                <div className="flex items-center gap-2 mb-6">
                  <span className="text-xs font-mono px-2 py-1 rounded-md bg-red-500/10 text-red-400 border border-red-500/20 tracking-widest uppercase">— before</span>
                  <span className="text-sm font-semibold text-white/50">Traditional Learning</span>
                </div>
                <ul className="space-y-3">
                  {['Static textbooks, no feedback','Practice with no explanations','No real-time code execution','Theory-only networking','No speech assessment','Manual progress tracking','Fixed difficulty for everyone'].map(t => (
                    <li key={t} className="flex items-start gap-3 text-sm text-white/35">
                      <span className="text-red-500/70 mt-0.5 flex-shrink-0 font-mono">-</span>{t}
                    </li>
                  ))}
                </ul>
              </div>
            </Reveal>

            <Reveal delay={0.12} x={30} y={0}>
              <div className="rounded-2xl p-6 h-full" style={{ background: 'linear-gradient(145deg,rgba(6,182,212,0.06),rgba(139,92,246,0.04))', backdropFilter: 'blur(20px)', border: '1px solid rgba(6,182,212,0.15)', boxShadow: '0 4px 32px rgba(6,182,212,0.06), inset 0 1px 0 rgba(255,255,255,0.10)' }}>
                <div className="flex items-center gap-2 mb-6">
                  <span className="text-xs font-mono px-2 py-1 rounded-md bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 tracking-widest uppercase">+ after</span>
                  <span className="text-sm font-semibold text-white/70">EduBot AI Platform</span>
                </div>
                <ul className="space-y-3">
                  {['AI questions tuned to your level','Instant explanations for every answer','In-browser code execution + AI review','Interactive drag-and-drop network sim','Real-time speech fluency scoring','Auto points, streaks, and levels','Adaptive difficulty that grows with you'].map(t => (
                    <li key={t} className="flex items-start gap-3 text-sm text-white/70">
                      <span className="text-cyan-400 mt-0.5 flex-shrink-0 font-mono">+</span>{t}
                    </li>
                  ))}
                </ul>
              </div>
            </Reveal>
          </div>
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="py-20 px-4 sm:px-6 relative overflow-hidden" style={{ background: 'linear-gradient(180deg,#0a0e1a 0%,#050810 60%,#000 100%)' }}>
        <div className="absolute inset-0 pointer-events-none" style={{ background: 'radial-gradient(ellipse 70% 60% at 50% 50%,rgba(6,182,212,0.08) 0%,transparent 70%)' }} />
        <Reveal className="relative z-10 max-w-xl mx-auto">
          <div className="text-center">
          <div className="text-xs font-mono text-cyan-400 uppercase tracking-widest mb-3">// ready to deploy?</div>
          <h2 className="text-3xl sm:text-5xl font-black mb-4 leading-tight">
            Start learning<br />
            <span style={{ background: 'linear-gradient(90deg,#22d3ee,#a78bfa)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>smarter today</span>
          </h2>
          <p className="text-white/40 text-base mb-8">Free to get started. No credit card required.</p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <motion.button whileHover={{ scale: 1.05, boxShadow: '0 0 40px rgba(6,182,212,0.5)' }} whileTap={{ scale: 0.97 }}
              onClick={() => navigate('/register')}
              className="px-8 py-3 font-bold text-sm rounded-xl text-gray-900 transition-all"
              style={{ background: 'linear-gradient(135deg,#22d3ee,#8b5cf6)', boxShadow: '0 0 24px rgba(6,182,212,0.3)' }}>
              Initialize Your Journey
            </motion.button>
            <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.97 }}
              onClick={() => navigate('/login')}
              className="px-8 py-3 font-semibold text-sm rounded-xl text-white/60 hover:text-white transition-all"
              style={{ border: '1px solid rgba(255,255,255,0.12)' }}>
              Log In
            </motion.button>
          </div>
          </div>
        </Reveal>
      </section>

      {/* ── Footer ── */}
      <footer className="px-6 py-10 border-t border-white/5" style={{ background: '#000' }}>
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md flex items-center justify-center text-xs font-black" style={{ background: 'linear-gradient(135deg,#06b6d4,#8b5cf6)' }}>E</div>
            <span className="text-sm font-bold font-mono text-white/50 tracking-widest">EDUBOT</span>
            <span className="text-white/20 text-xs font-mono ml-2">· Pillai College of Engineering</span>
          </div>
          <div className="flex gap-6 text-xs font-mono text-white/25 uppercase tracking-widest">
            {navLinks.map(({ id, label }) => (
              <button key={id} onClick={() => scrollTo(id)} className="hover:text-white/50 transition-colors">{label}</button>
            ))}
          </div>
          <div className="text-white/15 text-xs font-mono">© {new Date().getFullYear()}</div>
        </div>
      </footer>
    </div>
  )
}
